import { Check, ImagePlus, MessageCircle, X } from 'lucide-react'
import { ChangeEvent, useState } from 'react'
import { businessPhotoDescriptionLimit } from '../constants/portal'
import type { Business } from '../types/business'
import { formatCep } from '../utils/formatters'

type QuestionProps = { business: Business; update: (patch: Partial<Business>) => void; addPhotos: (event: ChangeEvent<HTMLInputElement>) => void; uploadLogo: (file: File) => Promise<string>; mediaUrl: (path: string | null) => string; validationMessage?: string }
export function WizardQuestion({ business, update, addPhotos, uploadLogo, mediaUrl, validationMessage }: QuestionProps) {
  const [cepLoading, setCepLoading] = useState(false)
  const [cepMessage, setCepMessage] = useState('')
  const toggleLocation = (option: 'fisico' | 'online') => {
    const current = business.location
    const location = current === 'ambos'
      ? option === 'fisico' ? 'online' : 'fisico'
      : current === option ? '' : current ? 'ambos' : option
    update({ location, ...(option === 'online' && location === 'online' ? { address: '' } : {}) })
  }
  const lookupCep = async () => {
    const cleanCep = business.cep.replace(/\D/g, '')
    if (cleanCep.length !== 8) { setCepMessage('Digite um CEP com 8 números.'); return }
    setCepLoading(true)
    setCepMessage('')
    try {
      const response = await fetch(`https://viacep.com.br/ws/${cleanCep}/json/`)
      const data = await response.json() as { erro?: boolean; logradouro?: string; bairro?: string; localidade?: string; uf?: string }
      if (data.erro) throw new Error('CEP não encontrado')
      update({ street: data.logradouro || '', neighborhood: data.bairro || '', city: `${data.localidade || ''} - ${data.uf || ''}`.replace(/^ - | - $/g, ''), cep: cleanCep })
    } catch { setCepMessage('Não foi possível encontrar esse CEP.') }
    finally { setCepLoading(false) }
  }
  if (business.step === 0) return <div className="question"><h2>Qual a área de atuação da sua empresa?</h2><p>Informe sua principal área de atuação. Você poderá detalhar seus serviços nas próximas etapas.</p><input autoFocus value={business.area} onChange={(event) => update({ area: event.target.value })} placeholder="Ex.: confeitaria, eletricista, consultoria em TI..." maxLength={150} /><span className={`field-counter${business.area.length > 135 ? ' near-limit' : ''}`}>{business.area.length}/150 caracteres</span></div>
  if (business.step === 1) return <div className="question"><h2>Como as pessoas vão reconhecer sua marca?</h2><p>Adicione uma foto ou logo e o nome fantasia.</p><label className="upload-logo">{business.logo ? <img src={mediaUrl(business.logo)} alt="Logo da empresa" /> : <ImagePlus size={25} />}<span>{business.logo ? 'Logo adicionada' : 'Adicionar foto ou logo'}</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { update({ logo: await uploadLogo(file) }) } catch { /* A mensagem é tratada pelo fluxo de upload. */ } event.target.value = '' }} /></label><input value={business.name} onChange={(event) => update({ name: event.target.value })} placeholder="Nome fantasia" required /></div>
  if (business.step === 2) return <div className="question"><h2>Onde você atende?</h2><p>Selecione uma ou as duas opções.</p><div className="choice-grid"><button className={business.location === 'fisico' || business.location === 'ambos' ? 'selected' : ''} onClick={() => toggleLocation('fisico')} aria-pressed={business.location === 'fisico' || business.location === 'ambos'}><strong>Local físico</strong><span>Recebo clientes em um endereço</span>{(business.location === 'fisico' || business.location === 'ambos') && <Check className="choice-check" size={18} />}</button><button className={business.location === 'online' || business.location === 'ambos' ? 'selected' : ''} onClick={() => toggleLocation('online')} aria-pressed={business.location === 'online' || business.location === 'ambos'}><strong>Atendimento online</strong><span>Atendo pela internet ou delivery</span>{(business.location === 'online' || business.location === 'ambos') && <Check className="choice-check" size={18} />}</button></div>{validationMessage && <p className="field-message">{validationMessage}</p>}<div className="cep-row"><input value={formatCep(business.cep || '')} onChange={(event) => update({ cep: event.target.value.replace(/\D/g, '').slice(0, 8) })} placeholder="CEP" inputMode="numeric" pattern="[0-9]{5}-[0-9]{3}" maxLength={9} /><button className="button button-outline" type="button" onClick={lookupCep} disabled={cepLoading}>{cepLoading ? 'Buscando...' : 'Buscar endereço'}</button></div>{cepMessage && <p className="field-message">{cepMessage}</p>}<input className="address-part" value={business.street} onChange={(event) => update({ street: event.target.value })} placeholder="Logradouro" required /><input className="address-part" value={business.neighborhood} onChange={(event) => update({ neighborhood: event.target.value })} placeholder="Bairro" required /><input className="address-part" value={business.city} onChange={(event) => update({ city: event.target.value })} placeholder="Cidade - UF" required /><div className="address-details"><input className="address-part" value={business.number} onChange={(event) => update({ number: event.target.value })} placeholder="Número" required /><input className="address-part" value={business.complement} onChange={(event) => update({ complement: event.target.value })} placeholder="Complemento (opcional)" /></div><label className="address-visibility"><input type="checkbox" checked={business.showAddress !== false} onChange={(event) => update({ showAddress: event.target.checked })} /> <span>Apresentar este endereço na página</span></label></div>
  if (business.step === 3) return <div className="question"><h2>Conte um pouco de você e da sua empresa.</h2><p>Capriche: esse texto ajuda as pessoas a se interessarem pelo seu trabalho.</p><textarea autoFocus value={business.story} onChange={(event) => update({ story: event.target.value })} placeholder="Como começou? O que torna seu trabalho especial?" rows={5} maxLength={1000} />{validationMessage && <p className="field-message">{validationMessage}</p>}<span className={`field-counter${business.story.length > 900 ? ' near-limit' : ''}`}>{business.story.length}/1000 caracteres</span></div>
  if (business.step === 4) { const photoLimitReached = business.photos.length >= 5; return <div className="question"><h2>Mostre o que você faz.</h2><p>Você pode adicionar até 5 fotos e descrever cada produto ou serviço.</p><label className={`photo-drop${photoLimitReached ? ' is-disabled' : ''}`}><ImagePlus size={25} /><strong>Adicionar fotos</strong><span>{business.photos.length}/5 fotos adicionadas</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={addPhotos} disabled={photoLimitReached} /></label>{photoLimitReached && <p className="field-message">Limite de 5 fotos atingido.</p>}<div className="photo-list">{business.photos.map((photo, index) => <div className="photo-item" key={photo.url}><img src={mediaUrl(photo.url)} alt="" /><div className="photo-description"><textarea value={photo.description} onChange={(event) => update({ photos: business.photos.map((item, itemIndex) => itemIndex === index ? { ...item, description: event.target.value } : item) })} placeholder="Descreva este produto ou serviço" aria-label={`Descrição da foto ${index + 1}`} rows={3} maxLength={businessPhotoDescriptionLimit} /><span className={`field-counter${photo.description.length > businessPhotoDescriptionLimit * .9 ? ' near-limit' : ''}`}>{photo.description.length} / {businessPhotoDescriptionLimit} caracteres</span></div><button onClick={() => update({ photos: business.photos.filter((_, itemIndex) => itemIndex !== index) })} aria-label="Remover foto"><X size={16} /></button></div>)}</div></div> }
  return <div className="question"><h2>Como seus clientes falam com você?</h2><p>Informe seus canais de contato.</p><label className="contact-field"><MessageCircle size={21} /><input autoFocus type="tel" value={business.whatsapp} onChange={(event) => update({ whatsapp: event.target.value })} placeholder="(73) 99999-9999" aria-label="Telefone do WhatsApp" /></label><label className="contact-field"><span className="email-symbol">@</span><input type="email" value={business.email} onChange={(event) => update({ email: event.target.value })} placeholder="seuemail@exemplo.com" aria-label="E-mail" /></label><div className="whatsapp-hint"><MessageCircle size={20} /><span>Depois de publicar, seus clientes poderão falar com você.</span></div></div>
}
